version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - "zookeeper"
  pyspark:
    build: ./pyspark
    volumes:
      - ./src:/home/jovyan/stream-analysis
    ports:
      - "8888:8888"
    links:
      - "kafka"
  sampler:
    build: ./src/reservoir_sampler
    volumes:
     - ./src/reservoir_sampler:/docker/sampler
    links:
      - "kafka"
    ports:
      - "8002:8002"
