version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - "zookeeper"
  pyspark:
    build: ./pyspark
    volumes:
      - ./src:/home/jovyan/stream-analysis
    ports:
      - "8888:8888"
    links:
      - "kafka"
      - "producer"
      - "sampler"
      - "cassandra"
  producer:
    build: ./src
    volumes:
     - ./src:/docker/app
    links:
      - "kafka"
    ports:
      - "8001:8001"
    command: ./run-dev.sh "-w twitter_producer" twitter_producer.manager
  sampler:
    build: ./src
    volumes:
     - ./src:/docker/app
    links:
      - "kafka"
    ports:
      - "8002:8002"
    command: ./run-dev.sh "-w reservoir_sampler" reservoir_sampler.manager
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
